packages:
  - 'packages/*'
allowBuilds:
  '@apollo/protobufjs': false
  '@nestjs/core': false
  '@parcel/watcher': false
  esbuild: false
  mongodb-memory-server: false
  sharp: false

overrides:
  'graphql': "16.11.0"
  "glob": "^8.0.0"
  "rimraf": "^3.0.0"
  "inflight": "1.0.6"
